// import 'package:flutter/cupertino.dart';

// import './models/articles.dart';

// final List<Articles> articles = [
//   Articles(
//     1,
//     "Guitare 1",
//     "This is an awesome article",
//     "Good",
//     5482,
//     2,
//     "instrument",
//     "Ludovic",
//   ),
//   Articles(
//     2,
//     "Guitare 2",
//     "This is an awesome article",
//     "Good",
//     5482,
//     2,
//     "instrument",
//     "Ludovic",
//   ),
//   Articles(
//     3,
//     "Guitare 3",
//     "This is an awesome article",
//     "Good",
//     5482,
//     2,
//     "instrument",
//     "Ludovic",
//   ),
//   Articles(
//     4,
//     "Guitare 4",
//     "This is an awesome article",
//     "Good",
//     5482,
//     2,
//     "instrument",
//     "Ludovic",
//   ),
//   Articles(
//     5,
//     "Guitare 5",
//     "This is an awesome article",
//     "Good",
//     5482,
//     2,
//     "instrument",
//     "Ludovic",
//   ),
//   Articles(
//     6,
//     "Guitare 6",
//     "This is an awesome article",
//     "Good",
//     5482,
//     2,
//     "instrument",
//     "Ludovic",
//   ),
//   Articles(
//     7,
//     "Guitare 7",
//     "This is an awesome article",
//     "Good",
//     5482,
//     2,
//     "instrument",
//     "Ludovic",
//   ),
//   Articles(
//     8,
//     "Guitare 8",
//     "This is an awesome article",
//     "Good",
//     5482,
//     2,
//     "instrument",
//     "Ludovic",
//   ),
//   Articles(
//     9,
//     "Guitare 9",
//     "This is an awesome article",
//     "Good",
//     5482,
//     2,
//     "instrument",
//     "Ludovic",
//   ),
//   Articles(
//     10,
//     "Guitare 10",
//     "This is an awesome article",
//     "Good",
//     5482,
//     2,
//     "instrument",
//     "Ludovic",
//   ),
// ];
