import 'package:flutter/cupertino.dart';

import './models/articles.dart';

final List<Articles> articles = [
  Articles(
    1,
    "Articles",
    "This is an awesome article",
    "Good",
    5482,
    2,
    "instrument",
    "Ludovic",
    Image.asset('assets/images/saxo.jpg'),
  ),
  Articles(
    2,
    "Articles",
    "This is an awesome article",
    "Good",
    5482,
    2,
    "instrument",
    "Ludovic",
    Image.asset('assets/images/saxo.jpg'),
  ),
  Articles(
    3,
    "Articles",
    "This is an awesome article",
    "Good",
    5482,
    2,
    "instrument",
    "Ludovic",
    Image.asset('assets/images/saxo.jpg'),
  ),
  Articles(
    4,
    "Articles",
    "This is an awesome article",
    "Good",
    5482,
    2,
    "instrument",
    "Ludovic",
    Image.asset('assets/images/saxo.jpg'),
  ),
  Articles(
    5,
    "Articles",
    "This is an awesome article",
    "Good",
    5482,
    2,
    "instrument",
    "Ludovic",
    Image.asset('assets/images/saxo.jpg'),
  ),
  Articles(
    6,
    "Articles",
    "This is an awesome article",
    "Good",
    5482,
    2,
    "instrument",
    "Ludovic",
    Image.asset('assets/images/saxo.jpg'),
  ),
  Articles(
    7,
    "Articles",
    "This is an awesome article",
    "Good",
    5482,
    2,
    "instrument",
    "Ludovic",
    Image.asset('assets/images/saxo.jpg'),
  ),
  Articles(
    8,
    "Articles",
    "This is an awesome article",
    "Good",
    5482,
    2,
    "instrument",
    "Ludovic",
    Image.asset('assets/images/saxo.jpg'),
  ),
  Articles(
    9,
    "Articles",
    "This is an awesome article",
    "Good",
    5482,
    2,
    "instrument",
    "Ludovic",
    Image.asset('assets/images/saxo.jpg'),
  ),
  Articles(
    10,
    "Articles",
    "This is an awesome article",
    "Good",
    5482,
    2,
    "instrument",
    "Ludovic",
    Image.asset('assets/images/saxo.jpg'),
  ),
];
